### PR TITLE
Pass match_water parameter to specialised solvation functions

### LINKED ISSUE #185: [BUG] match_water parameter not passed through to solvation function
When calling the generic `BioSimSpace.Solvent.solvate` function, the `match_water` parameter isn't passed through to the specialised water model function.

### PR DESCRIPTION
**Pull request by lohedges**
This PR fixes a bug where the `match_water` parameter wasn't passed from the generic `BioSimSpace.Solvent.solvate` function through to the specialised functions for the supported water models. I've generalised the test so it uses both function types so that we catch similarly missed parameters in future, e.g. when anything else is added.

Closes #185.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

### CODE REVIEW

**Comment by lohedges** [comment]
The CI won't currently work since there are no Sire 2023.5.0.dev packages on our conda channel. I'll re-run once the `feature_optimise_openmm` branch is merged.

**Comment by chryswoods** [comment]
I'm happy to merge that if you are happy to review?

**Comment by lohedges** [comment]
Yes, no problem. I'll take a closer look tomorrow but I've been using it today without issue.

**Comment by xiki-tempula** [comment]
Do you mind give me a ping when the fix has been propagated to the main branch please? Thank you.

**Comment by lohedges** [comment]
No problem. This is just waiting on the Sire PR to be merged. I'm going though that now, so should be done today/tomorrow.

**Comment by lohedges** [comment]
Closing since I somehow branched off `main` rather than `devel`. This isn't too much of an issue since this is the first change since the release, but I'll re-open with a new branch to do things properly.

**Comment by lohedges** [comment]
@xiki-tempula: This has now been backported to `main`.

**Comment by xiki-tempula** [comment]
Excellent Thanks.

**Pull request closed without merging**
