### PR TITLE
Add Protein FEP tutorial

### PR DESCRIPTION
**Pull request by akalpokas**
This PR adds a tutorial detailing the new protein FEP functionality, which explores a simple ubiquitin mutation, and a more complex set up for an aldose reductase mutation. Happy to make changes if needed!

TODO: Update tutorial input file paths before merging

### CODE REVIEW

**Review by lohedges — APPROVED** [review]
Thanks, this is fantastic. Let me know what additional files you'd like to include and I'll update them to the website so you can replace the `input_files` paths with URLs.

**Comment by lohedges** [comment]
I forgot that you sent me the files. I'll upload to the website and update the links. I've merge your branch in locally so this will automatically be closed when I merge.

Cheers.

**Comment by lohedges** [comment]
I've now replaced the links and have tested locally. If you're able to take a quick look and I'll merge tomorrow when you're happy.

**Comment by akalpokas** [comment]
I tested the tutorial with the updated links and it all looks good to me. Thanks for your help!

**Pull request merged**
