### PR TITLE
Feature reduce

### PR DESCRIPTION
**Pull request by lohedges**
This PR exposes functionality related to the changes to `sire.legacy.Vol.TriclinicBox`, allowing the user to manually rotate the space and perform a lattice reduction. Keywords have also been added to `BioSimSpace.IO.readMolecules` to allow the user to perform these operations on load.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a test for any new functionality in this pull request: [y]
* I confirm that I have added documentation (e.g. a new tutorial page or detailed guide) for any new functionality in this pull request: [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

### CODE REVIEW

**Review by chryswoods — DISMISSED** [review]
Looks good. I think it is good that we assume the perturbable properties are called xxx0 and xxx1 (as you've done to find the perturbable molecules coordinates and velocities properties). The user has freedom to use other names, but it makes the code more difficult. I've said this is the format in the new sire docs for merged molecules. It may be worth separately creating a "detailed guide" page on the BioSimSpace website describing the merged molecule layout and format.

**Comment by lohedges** [comment]
Yes, that's a good point. I allow the user to pass a map when performing the merge (if the system has different names) but then it just uses what it finds and appends 0 and 1.

**Comment by lohedges** [comment]
Hmm, apparently the updated test angles weren't on this branch, despite me merging across from `devel`. Will see what went wrong.

**Comment by lohedges** [comment]
Nope, the change is there and it's built against the most recent development version of Sire. Will debug locally. I can't see that the recent Sire merge has somehow reverted the triclinic update?

**Comment by lohedges** [comment]
(No, not possible since other tests would fail here.)

**Comment by lohedges** [comment]
Ah, the issue is that the test _works_ if you run it in isolation (as I was doing) but not if you run them all. Presumably the space is being modified by another test. Will fix and repush.

**Pull request merged**
