### PR TITLE
Improve robustness of restraint search and fix torsional force constant bug

### PR DESCRIPTION
**Pull request by fjclark**
# Is this pull request to fix a bug, or to introduce new functionality?

This PR does two things:

1. Fixes https://github.com/OpenBioSim/biosimspace/issues/359
2. Improves the robustness of the ABFE restraint search to strange user input. I've implemented the improvements discussed [here](https://github.com/OpenBioSim/biosimspace_tutorials/issues/28#issuecomment-2434686918). 

I've included the two together to reduce CI runs/ faff, but please let me know if I should create separate PRs in future.

## If this is to fix a bug...

This pull request fixes issue #359?

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

Note that the ordering of candidate anchor points in the restraint search will be slightly different now, as the torsions have less weight when ordering the restraints for selection.

## If this introduces new functionality...

Changes proposed in this pull request:

I now:

 - Ensure that anchors can never be in the same molecule
 - Warn the user if they select the protein/water as the "ligand"
 - Warn the user if they supply very few frames for fitting

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a test for any new functionality in this pull request: [y]
* I confirm that I have added documentation (e.g. a new tutorial page or detailed guide) for any new functionality in this pull request: [n]
* I confirm that I have permission to release this code under the GPL3 license: [y]

The tests could be more comprehensive - at the moment I've only added a test to check that an error is raised if the receptor and ligand candidate anchor point lists share atoms. I haven't included tests to check that the correct warnings are being raised. The reason for this was that the only trajectory I can find on the website (https://github.com/OpenBioSim/biosimspace_website/tree/main/structures) only includes the ligand and the protein. This means that I can't select weird "ligands" which aren't the ligand or protein (e.g. water) which don't raise errors for other reasons. If we'd like more complete tests, we could always add a trajectory with e.g. 1 water molecule as well as the complex. However, I have verified that these warnings are raised for one of my test systems, and the code for these checks is very simple.

## Suggested reviewers:
@lohedges 

Thanks.

### CODE REVIEW

**Comment by lohedges** [comment]
Thanks for this. The CI is failing because there isn't yet a 2024.4.0.dev Sire package. I'll trigger the CI for that now.

**Comment by lohedges** [comment]
Not sure what's going on, but it appears that you might have merged in `devel` without actually taking the changes, i.e. using `ours`. This is why the CI is failing, since you are still building against the old version of Sire. (Although the packages should still be available.) For example, [this](https://github.com/fjclark/biosimspace-openbiosim/blob/feature-robust-restraint-search/requirements.txt) requirements files appears to be the one from `main`, not `devel`. I think this might also explain the weird diff with the website index file, which is proposing changes which are _already_ in `devel`.

**Comment by fjclark** [comment]
Sorry, not sure what I've done to cause this. Double-checking that my `devel` was in sync with OBS, pulling again, and merging again changed only `requirements.txt`:

image

**Comment by lohedges** [comment]
No problem. Things look correct now. Ignore the Windows failure, although the CI passed, it crashed when uploading the package to the Anaconda cloud. The Linux 3.12 failure is due to black formatting. (I need to switch to pre-commit at some point so the linting/formatting is automated.)

**Review by lohedges — APPROVED** [review]
Thanks, @fjclark. This looks great and will make the restraint selection a lot more reliable.

**Pull request merged**
