### PR TITLE
Backport fixes from PR #210.

### PR DESCRIPTION
**Pull request by lohedges**
This PR backports the fixes from #210 into `main`.

* I confirm that I have merged the latest version of `main` into this branch before issuing this pull request (e.g. by running `git pull origin main`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

### CODE REVIEW

**Comment by lohedges** [comment]
CI is failing since it looks like some of the Sire _fixes_ were PRed as _features_, thus never backported. In particular, [this](https://github.com/OpenBioSim/sire/pull/119) and [this](https://github.com/OpenBioSim/sire/pull/120).

**Comment by chryswoods** [comment]
Sorry - I don't know what I was thinking when I made them features... Do you still want them backported, or is it ok to have these fixes in just 2023.5.0?

**Comment by chryswoods** [comment]
I see what happened - I had them as issue branches, but combined several together into the merge into devel with a feature, as I wanted to save the CI. Because they went in merged with the feature, I forgot to backport the individual fixes to main.

**Comment by lohedges** [comment]
No problem, it's easily done. If I don't do them immediately then I forget. I'm happy to wait until the release unless it's needed by Exs before, e.g. perhaps they will be using 2023.4 for a bit and need a working version. I wasn't planning on doing another BioSimSpace patch release. At present, I think the existing `main` branch of BioSimSpace is broken, since there is no compatible version of Sire, i.e. I merged in my fixes assuming that the Sire updates to which they were related were already backported. Guess it might be worth checking with @xiki-tempula.

**Comment by xiki-tempula** [comment]
Thanks for mentioning me. So we are currently basing our main to the Sire main (as we need to some fix from the main), which is not the Sire 2023.4.1. I wonder when you make them sync, would it cause trouble if we are using the main (potentially 2023.4.2)? Thanks.

**Comment by lohedges** [comment]
I don't think there will be any issue. Currently BIoSimSpace `main` is broken since there are backports that rely on functionality that isn't in Sire `main`. (These are minor updates to do with rotatiing boxes and the Sire trajectory analysis.) Once these are merged into Sire `main`, then all is okay.

**Comment by chryswoods** [comment]
It shouldn't - the PR for the fixes into `main` passes all CI. If @lohedges is happy, I will merge that in today and will prepare the 2023.4.2 release. We can then merge this PR into `main` on BioSimSpace and maybe do a patch release too?

**Comment by xiki-tempula** [comment]
Great. Thanks.

**Comment by lohedges** [comment]
Great. I'm off for part of the day but will try to review when I'm back. I've stacked a few other backports into this PR too. @xiki-tempula, do you want [this](https://github.com/OpenBioSim/biosimspace/pull/222) one added too. (The one related to the AMBER mask.)

**Comment by xiki-tempula** [comment]
Yes, please. Thanks.

**Comment by lohedges** [comment]
All passing now that I'm building against Sire 2023.4.2 :+1: I'd just like to figure out what to do about the backport for #226, then I'll be able to create a BioSimSpace 2023.4.1 release. @chryswoods, do you have any opinions on that?

**Pull request merged**
