### PR TITLE
Add fkcombu as dependency

### PR DESCRIPTION
**Pull request by fjclark**
Hi,

I found that tests were failing as fkcombu was not installed after running `python setup.py install` - this PR fixes that.

Thanks.

### CODE REVIEW

**Comment by lohedges** [comment]
It should be installed via `kcombu_bss`. I'll check what's gone wrong. It certainly works if you set up a Sire development environment first.

**Comment by fjclark** [comment]
Ah sorry, my mistake - I tried to shortcut the Sire install by installing through conda.

**Comment by fjclark** [comment]
OK, thanks for the clarification. I was installing Sire into a conda environment and then installing BioSimSpace on top of that, with:

```python
mamba create -n openbiosim-dev "python<3.10"
mamba activate openbiosim-dev
mamba install -c openbiosim/label/dev sire
git clone https://github.com/openbiosim/biosimspace:
cd biosimspace/python
python setup.py install
mamba install fkcombu
cd ..
mamba install pytest
pytest test
```

The idea was that we will be frequently changing BSS, but plan to leave Sire alone. To be completely clear - is the above installation fine, or would it be better to install Sire from source even if we do not plan to modify it? Thanks.

**Comment by lohedges** [comment]
I think the easiest approach would be to conda install BioSimSpace rather than Sire, then do a development install of BioSimSpace within that environment, skipping the re-installation of the BioSImSpace dependencies. The `setup.py` script pre-dates the move to conda, so I think I need to re-work it in light of how things are currently done.

```
mamba create -n openbiosim-dev -c conda-forge -c openbiosim/label/dev python=3.9 biosimspace pytest
mamba activate openbiosim-dev
git clone https://github.com/openbiosim/biosimspace
cd biosimspace/python
BSS_SKIP_DEPDENCIES=1 python setup.py develop
cd ..
pytest test
```

Note that I  install `sire` and `pytest` at the environment creation stage. This is the approach recommended by conda/mamba since it is easier for the solver, i.e. you are resolving the all dependencies when the environment is created, not creating a base environment, then installing things into it. Also, I've explicitly specified the python version just so I know what I'll end up with. Feel free to change this if you require a lower version. (At present we support `py38` and `py39` and should be able to add `py310` later this year.)

Let me know if this doesn't work.

**Comment by fjclark** [comment]
Thanks very much for this. After following the steps you give above, several of the Exscientia tests raised software incompatibility errors related to OFF 2, as a result of not having ambertools in the environment (specifically that antechamber was missing). 

I then tried running ` python setup.py install`, and ambertools was installed:

```
The following NEW packages will be INSTALLED:

  ambertools         conda-forge/linux-64::ambertools-22.0-py39h464e725_3 None
  arpack             conda-forge/linux-64::arpack-3.7.0-hdefa2d7_2 None
  cython             conda-forge/linux-64::cython-0.29.33-py39h227be39_0 None
  netcdf-fortran     conda-forge/linux-64::netcdf-fortran-4.6.0-nompi_he1eeb6f_102 None
  openff-interchange conda-forge/noarch::openff-interchange-0.2.3-pyhd8ed1ab_1 None
  openff-toolkit     conda-forge/noarch::openff-toolkit-0.12.0-pyhd8ed1ab_0 None
  packmol            conda-forge/linux-64::packmol-20.010-h86c2bf4_0 None
  panedr             conda-forge/noarch::panedr-0.7.1-pyhd8ed1ab_0 None
  perl               conda-forge/linux-64::perl-5.32.1-2_h7f98852_perl5 None
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.2.1-h7f98852_2 None

The following packages will be SUPERSEDED by a higher-priority channel:

  biosimspace        openbiosim/label/dev::biosimspace-202~ --> michellab/label/dev::biosimspace-2023.1.1-py39_0 None
  kcombu_bss         openbiosim/label/dev::kcombu_bss-2023~ --> michellab/label/dev::kcombu_bss-2022.06.10-h9bf148f_0 None
  sire               openbiosim/label/dev::sire-2023.1.2-p~ --> michellab/label/dev::sire-2023.1.1-py39h3fd9d12_2 None

The following packages will be DOWNGRADED:

  openmm                               8.0.0-py39hc5dd2c2_0 --> 7.7.0-py39h15fbce5_1 None
  parmed                               4.0.0-py39h227be39_0 --> 3.4.4-py39h227be39_0 None
```

However, I then got the following test failures:

```
FAILED test/IO/test_file_cache.py::test_file_cache - AttributeError: module 'BioSimSpace.IO' has no attribute '_file_cache'
FAILED test/Sandpit/Exscientia/IO/test_file_cache.py::test_file_cache - AttributeError: module 'BioSimSpace.Sandpit.Exscientia.IO' has no attribute '_file_cache'
FAILED test/Sandpit/Exscientia/_SireWrappers/test_system.py::test_isSame - AttributeError: 'System' object has no attribute 'isSame'
FAILED test/_SireWrappers/test_system.py::test_isSame - AttributeError: 'System' object has no attribute 'isSame'
========================================= 4 failed, 874 passed, 68 skipped, 10 xfailed, 208 warnings in 808.52s (0:13:28) =========================================
```

**Comment by lohedges** [comment]
Sorry, I assumed that you had your own external AmberTools installed. If you want to use the conda-forge packages, with which Sire/BioSimSpace are compatible, then just add `ambertools` and `gromacs` to the `mamba` create line. These are optional. That said, the tests should be guarded against them being missing, so I'm surprised it failed.

Can you confirm what version of BioSimSpace you are installing after setting up the environment. All tests are passing on `devel`, so I'm not sure why you're missing the `isSame` attribute. I'm wondering if the BioSimSpace that was first installed is outdated and taking precedence. Could you try recreating the environment using the `--only-deps` option for BioSimSpace. With this, you might need to setup the environment in two steps, i.e.

```
mamba create -n openbiosim-dev -c conda-forge -c openbiosim/label/dev python=3.9 biosimspace --only-deps
mamba activate openbiosim-dev
mamba install -c conda-forge ambertools gromacs pytest
```

**Comment by lohedges** [comment]
I just realised that `ambertools` will be installed when using `python setup.py install` since I hadn't reverted the requirements to use the `openf-toolkit-base` package, which doesn't depend on it. I've updated this now so that it completely matches the `requirements.txt` file. (Will update at some point so it just parses this file.)

That said, don't use `setup.py install`, do this instead:

```
BSS_SKIP_DEPDENCIES=1 python setup.py develop
```

This will give you an editable local development install, using the dependencies already installed in the environment when it was created.

I've had a quick check and do think the test failures that you are seeing are due to an outdated version of BioSimSpace being installed during the environment resolution, i.e. one without the `isSame` functionality, which is inconsistent with the latest tests that you are running.

The following works for me:

```
mamba create -n openbiosim-dev -c conda-forge -c openbiosim/label/dev biosimspace --only-deps
mamba activate openbiosim-dev
mamba install -c conda-forge ambertools gromacs pytest
git clone https://github.com/openbiosim/biosimspace
cd biosimspace/python
BSS_SKIP_DEPDENCIES=1 python setup.py develop
cd ..
pytest test
```

**Comment by fjclark** [comment]
That works - thanks very much!

**Comment by lohedges** [comment]
Great, I've updated the developer installation guide accordingly, since I doubt many people will want to do a full blown Sire install.

**Pull request closed without merging**
