### PR TITLE
Add unified FEP analysis using alchemlyb

### PR DESCRIPTION
**Pull request by lohedges**
This PR ports @annamherz's FEP analysis from the [feature-analysis](https://github.com/michellab/BioSimSpace/tree/feature-analysis) branch of the legacy michellab repo. This is a necessary first step to allow the porting of AMBER FEP and ABFE from the Exscientia sandpit.

In comparison with the original michellab branch there are a few notable changes:

* The estimator is no longer an option to the `FreeEnergy.Relative` constructor. Since the analysis is entirely independent from the simulation and can be run statically on existing output there is no need for the estimator to be specified when an instance is created. (This would only be needed if the estimator changed the actual output of the simulation.)
* I've refactored to reduce code duplication and ease future maintenance. For example, there is now a single `_somd_extract` method that takes the estimator as a parameter. Combining this with `itertools.partial`, it's possible to create a callable with the expected signature in the function from which it is called.
* I've removed the plotting functionality since the overlap can already be shown using the [BioSimSpace.Notebook.plotOverlap](https://github.com/OpenBioSim/biosimspace/blob/8d11aec199aa2c309b6306ad34616b479b9243fe/python/BioSimSpace/Notebook/_plot.py#L538) function. In doing so, I decided to always return `None` for the overlap when the chosen estimator (or method) wouldn't return one, rather than returning something different for TI. Returning different data types, or adding support for more plotting functionality is something that we can consider at a later date.
* I've added a [unit test](https://github.com/OpenBioSim/biosimspace/blob/68a13d49a4e4db88d0c246b9b35faaeba340025c/tests/FreeEnergy/test_relative.py#L52-L95) that runs analysis against some existing output data to ensure that the results are as expected. Thanks to @annamherz for testing using your local branch to ensure that we were both getting the same numbers.

Once this is approved and merged, please direct any future development work, e.g. bug-fixes, improvements, to this repo.

Closes michellab/BioSimSpace#365.

## Checklist:

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a test for any new functionality in this pull request: [y]
* I confirm that I have added documentation (e.g. a new tutorial page or detailed guide) for any new functionality in this pull request: [y] (Already documented, this just changes the backend used by the existing API.)
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@annamherz

### CODE REVIEW

**Comment by lohedges** [comment]
This seems to repeatedly fail on Python 3.9 (with the same dependency versions). I'll need to debug locally. The windows tests appear to fail because the glob logic for working out the list of output files is failing, presumably due to the use of a forward slash in the split command. I'll see if this can be made OS agnostic.

**Comment by lohedges** [comment]
Phew, thankfully both issues were easy to fix. All appears to be working now.

**Comment by annamherz** [comment]
Hello! Would it be possible to keep a function similar to get_u_nk as in [this recent commit](https://github.com/michellab/BioSimSpace/commit/a6933302f545b83ce72b595d11bdad84c29852ab), as for some more advanced analysis I need to be able to get the extracted raw df? This is probably more cumbersome in the code but I think could potentially be useful for future code changes as well?

**Comment by lohedges** [comment]
Yes, no problem, I'll add that this afternoon.

**Review by annamherz — APPROVED** [review]
Hello, sorry for the delay! I added some tiny fixes but these needed to be opened in a PR (https://github.com/OpenBioSim/biosimspace/pull/182)

**Comment by lohedges** [comment]
Thanks, @annamherz, much appreciated. The fixes look good, will merge them in when I'm at the computer. That was the correct way to submit, i.e. fork from my branch then PR against it.

**Pull request merged**
