### PR TITLE
Fix issue #280

### LINKED ISSUE #280: [BUG] getFrame space check incorrecty uses self
As in the title, the check for a space property in this function incorrectly uses `self`, presumably because the logic was copied from the `Trajectory` class.

### PR DESCRIPTION
**Pull request by lohedges**
This PR closes #280.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

Note that I expect the CI to fail on macOS due to [this](https://github.com/OpenBioSim/sire/issues/193) issue.

### CODE REVIEW

**Comment by lohedges** [comment]
Well, that was strange. The macOS build did indeed fail, but not for the reason that I was expecting. The error is:

```
 The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested sire 2024.2.0.dev
```

The package [does exist](https://anaconda.org/openbiosim/sire/2024.2.0.dev/download/osx-64/sire-2024.2.0.dev-py310h01edc0c_46.tar.bz2), so I don't know why it wasn't found. Will try re-running.

**Comment by lohedges** [comment]
Same issue with a re-run. Really strange.

**Comment by lohedges** [comment]
I see the issue, the runner is now `osx-arm64`. This must be the origin of the GROMACS issue too!

**Comment by xiki-tempula** [comment]
Hi @lohedges Is this PR ready? Do you mind merge this, please? Thanks.

**Comment by lohedges** [comment]
The Windows re-run passed. Everything should be good once the macOS ARM64 sire package is ready. If easier, we can always merge once reviewed and rebuild against the updated packages once available.

**Comment by xiki-tempula** [comment]
Do you mind merge this now, please? Thank you.

**Comment by lohedges** [comment]
@mb2055: Are you able to review?

@xiki-tempula: I've already mentioned twice that we need a review for this. We have an internal process to follow with a limited team who are busy working on other things. I see that you have already manually applied on of the fixes here to your own fork, i.e. in [this](https://github.com/OpenBioSim/biosimspace/commit/61feddc8b7dadeafb53be5595fb5bb9a90bd4287) commit. I know your fork is based from our `main`, but is there a reason that you can't apply patches from fix PRs for things that are blocking you? (It seems that you do manually add certain fixes, but not others.)

**Comment by mb2055** [comment]
Sure thing, I'll go through it now

**Comment by lohedges** [comment]
No problem. For fixes like this it is probably best (in future) that someone from your end reviews it, since you have a detailed understanding of the issue and can easily test if it works. I think you can add reviews (you have done before) but aren't available from the drop-down for some reason. (Presumably I need to adjust the permissions.)

**Comment by xiki-tempula** [comment]
Thanks for mentioning it. I always thought that only the OBS people can be asked to review these PRs.

**Review by mb2055 — APPROVED** [review]
Everything working on my end :+1:  sounds like everything is working for @xiki-tempula so it should be good to go

**Pull request merged**
